Update LACT.SlackBuild

diff --git a/LACT/LACT.SlackBuild b/LACT/LACT.SlackBuild
--- a/LACT/LACT.SlackBuild
+++ b/LACT/LACT.SlackBuild
@@ -78,7 +78,34 @@ find -L . \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
   -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-make build-release ; make install DESTDIR=$PKG PREFIX=/usr
+# Check if libadwaita is available
+if pkg-config --exists libadwaita; then
+    LIBADWAITA_FLAGS=$(pkg-config --cflags --libs libadwaita)
+    echo "Building with libadwaita support"
+make build-release --features=adw CPPFLAGS="$LIBADWAITA_FLAGS" ; make install DESTDIR=$PKG PREFIX=/usr
+
+install -vDm 0755 $CWD/rc.lact -t $PKG/etc/rc.d/
+mv $PKG/etc/rc.d/{rc.lact,rc.lact.new}
+
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION-ADW
+cp -a README.md LICENSE API.md \
+    $PKG/usr/doc/$PRGNAM-$VERSION-ADW
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION-ADW/$PRGNAM.SlackBuild
+
+mkdir -p $PKG/install
+cat $CWD/slack-desc.adw > $PKG/install/slack-desc
+zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
+
+cd $PKG
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-ADW-$ARCH-$BUILD$TAG.$PKGTYPE
+sleep 3
+echo "Building without libadwaita"
+cd $TMP
+cd $PRGNAM-$VERSION
+make build-release CPPFLAGS="$LIBADWAITA_FLAGS" ; make install DESTDIR=$PKG PREFIX=/usr
 
 install -vDm 0755 $CWD/rc.lact -t $PKG/etc/rc.d/
 mv $PKG/etc/rc.d/{rc.lact,rc.lact.new}
@@ -93,7 +120,31 @@ cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
-#zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
+zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+
+else
+    echo "libadwaita not found, building without it"
+make build-release CPPFLAGS="$LIBADWAITA_FLAGS" ; make install DESTDIR=$PKG PREFIX=/usr
+
+install -vDm 0755 $CWD/rc.lact -t $PKG/etc/rc.d/
+mv $PKG/etc/rc.d/{rc.lact,rc.lact.new}
+
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
+  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a README.md LICENSE API.md \
+    $PKG/usr/doc/$PRGNAM-$VERSION
+cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+
+mkdir -p $PKG/install
+cat $CWD/slack-desc > $PKG/install/slack-desc
+zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh
+
+cd $PKG
+/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
+
+fi
